window.CHAEA_QUESTIONS = [
  { id: 1, texto: "Tengo fama de decir lo que pienso claramente y sin rodeos." },
  { id: 2, texto: "Estoy seguro/a de lo que es bueno y lo que es malo, lo que está bien y lo que está mal." },
  { id: 3, texto: "Muchas veces actúo sin mirar las consecuencias." },
  { id: 4, texto: "Normalmente trato de resolver los problemas metódicamente y paso a paso." },
  { id: 5, texto: "Creo que los formalismos coartan y limitan la actuación libre de las personas." },
  { id: 6, texto: "Me interesa saber cuáles son los sistemas de valores de los demás y con qué criterios actúan." },
  { id: 7, texto: "Pienso que el actuar intuitivamente puede ser siempre tan válido como actuar reflexivamente." },
  { id: 8, texto: "Creo que lo más importante es que las cosas funcionen." },
  { id: 9, texto: "Procuro estar al tanto de lo que ocurre aquí y ahora." },
  { id: 10, texto: "Disfruto cuando tengo tiempo para preparar mi trabajo y realizado a conciencia." },
  { id: 11, texto: "Estoy a gusto siguiendo un orden, en las comidas, en el estudio, haciendo ejercicio regularmente." },
  { id: 12, texto: "Cuando escucho una nueva idea enseguida comienzo a pensar cómo ponerla en práctica." },
  { id: 13, texto: "Prefiero las ideas originales y novedosas aunque no sean prácticas." },
  { id: 14, texto: "Admito y me ajusto a las normas sólo si me sirven para lograr mis objetivos." },
  { id: 15, texto: "Normalmente encajo bien con personas reflexivas, y me cuesta sintonizar con personas demasiado espontáneas, imprevisibles." },
  { id: 16, texto: "Escucho con más frecuencia que hablo." },
  { id: 17, texto: "Prefiero las cosas estructuradas a las desordenadas." },
  { id: 18, texto: "Cuando poseo cualquier información, trato de interpretada bien antes de manifestar alguna conclusión." },
  { id: 19, texto: "Antes de hacer algo estudio con cuidado sus ventajas e inconvenientes." },
  { id: 20, texto: "Me crezco con el reto de hacer algo nuevo y diferente." },
  { id: 21, texto: "Casi siempre procuro ser coherente con mis criterios y sistemas de valores. Tengo principios y los sigo." },
  { id: 22, texto: "Cuando hay una discusión no me gusta ir con rodeos." },
  { id: 23, texto: "Me disgusta implicarme afectivamente en mi ambiente de trabajo. Prefiero mantener relaciones distantes." },
  { id: 24, texto: "Me gustan más las personas realistas y concretas que las teóricas." },
  { id: 25, texto: "Me cuesta ser creativo/a, romper estructuras." },
  { id: 26, texto: "Me siento a gusto con personas espontáneas y divertidas." },
  { id: 27, texto: "La mayoría de las veces expreso abiertamente cómo me siento." },
  { id: 28, texto: "Me gusta analizar y dar vueltas a las cosas." },
  { id: 29, texto: "Me molesta que la gente no se tome en serio las cosas." },
  { id: 30, texto: "Me atrae experimentar y practicar las últimas técnicas y novedades." },
  { id: 31, texto: "Soy cauteloso/a a la hora de sacar conclusiones." },
  { id: 32, texto: "Prefiero contar con el mayor número de fuentes de información. Cuantos más datos reúna para reflexionar, mejor." },
  { id: 33, texto: "Tiendo a ser perfeccionista." },
  { id: 34, texto: "Prefiero oír las opiniones de los demás antes de exponer la mía." },
  { id: 35, texto: "Me gusta afrontar la vida espontáneamente y no tener que planificar todo previamente." },
  { id: 36, texto: "En las discusiones me gusta observar cómo actúan los demás participantes." },
  { id: 37, texto: "Me siento incómodo/a con las personas calladas y demasiado analíticas." },
  { id: 38, texto: "Juzgo con frecuencia las ideas de los demás por su valor práctico." },
  { id: 39, texto: "Me agobio. si me obligan a acelerar mucho el trabajo para cumplir un plazo." },
  { id: 40, texto: "En las reuniones apoyo las ideas prácticas y realistas." },
  { id: 41, texto: "Es mejor gozar del momento presente que deleitarse pensando en el pasado o en el futuro." },
  { id: 42, texto: "Me molestan las personas que siempre desean apresurar las cosas." },
  { id: 43, texto: "Aporto ideas nuevas y espontáneas en los grupos de discusión." },
  { id: 44, texto: "Pienso que son más consistentes las decisiones fundamentadas en un minucioso análisis que las basadas en la intuición." },
  { id: 45, texto: "Detecto frecuentemente la inconsistencia y puntos débiles en las argumentaciones de los demás." },
  { id: 46, texto: "Creo que es preciso saltarse las normas muchas más veces que cumplidas." },
  { id: 47, texto: "A menudo caigo en la cuenta de otras formas mejores y más prácticas de hacer las cosas." },
  { id: 48, texto: "En conjunto hablo más que escucho." },
  { id: 49, texto: "Prefiero distanciarme de los hechos y observados desde otras perspectivas." },
  { id: 50, texto: "Estoy convencido/a que debe imponerse la lógica y el razonamiento." },
  { id: 51, texto: "Me gusta buscar nuevas experiencias." },
  { id: 52, texto: "Me gusta experimentar y aplicar las cosas." },
  { id: 53, texto: "Pienso que debemos llegar pronto al grano, al meollo de los temas." },
  { id: 54, texto: "Siempre trato de conseguir conclusiones e ideas claras." },
  { id: 55, texto: "Prefiero discutir cuestiones concretas y no perder el tiempo con charlas vacías." },
  { id: 56, texto: "Me impaciento cuando me dan explicaciones irrelevantes e incoherentes." },
  { id: 57, texto: "Compruebo antes si las cosas funcionan realmente." },
  { id: 58, texto: "Hago varios borradores antes de la redacción definitiva de un trabajo." },
  { id: 59, texto: "Soy consciente de que en las discusiones ayudo a mantener a los demás centrados en el tema, evitando divagaciones." },
  { id: 60, texto: "Observo que, con frecuencia, soy uno/a de los/as más objetivos/as y desapasionados/as en las discusiones." },
  { id: 61, texto: "Cuando algo va mal, le quito importancia y trato de hacerla mejor." },
  { id: 62, texto: "Rechazo ideas originales y espontáneas si no las veo prácticas." },
  { id: 63, texto: "Me gusta sopesar diversas alternativas antes de tomar una decisión." },
  { id: 64, texto: "Con frecuencia miro hacia adelante para prever el futuro." },
  { id: 65, texto: "En los debates y discusiones prefiero desempeñar un papel secundario antes que ser el/la líder o el/la que más participa." },
  { id: 66, texto: "Me molestan las personas que no actúan con lógica." },
  { id: 67, texto: "Me resulta incómodo tener que planificar y prever las cosas." },
  { id: 68, texto: "Creo que el fin justifica los medios en muchos casos." },
  { id: 69, texto: "Suelo reflexionar sobre los asuntos y problemas." },
  { id: 70, texto: "El trabajar a conciencia me llena de satisfacción y orgullo." },
  { id: 71, texto: "Ante los acontecimientos trato de descubrir los principios y teorías en que se basan." },
  { id: 72, texto: "Con tal de conseguir el objetivo que pretendo soy capaz de herir sentimientos ajenos." },
  { id: 73, texto: "No me importa hacer todo lo necesario para que sea efectivo mi trabajo." },
  { id: 74, texto: "Con frecuencia soy una de las personas que más anima las fiestas." },
  { id: 75, texto: "Me aburro enseguida con el trabajo metódico y minucioso." },
  { id: 76, texto: "La gente con frecuencia cree que soy poco sensible a sus sentimientos." },
  { id: 77, texto: "Suelo dejarme llevar por mis intuiciones." },
  { id: 78, texto: "Si trabajo en grupo procuro que se siga un método y un orden." },
  { id: 79, texto: "Con frecuencia me interesa averiguar lo que piensa la gente." },
  { id: 80, texto: "Esquivo los temas subjetivos, ambiguos y poco claros." },
];
