/**
 * EMI Microteaching Data: Electric Charges and Fields Workshop
 * Strictly adheres to AGENTS.md pedagogical schema (19 required fields per dictionary item + LaTeX formula).
 * Complete frequency and category breakdown across all 35 terms of the video:
 * - High-Frequency Core Words (`Palabras que más salen`)
 * - Essential Discourse Connectors (`Los conectores que más salen`)
 * - Low-Frequency / Rare Academic Terms (`Las palabras que menos salen`)
 */

const MICROTEACHING_VOCABULARY = [
    // --- HIGH-FREQUENCY CORE NOUNS (`Palabras que más salen`) ---
    {
        id: "vocab-1",
        term: "charge",
        ipa: "/tʃɑːrdʒ/",
        pos: "Noun",
        group: "Electrostatics • 🔥 Top High Frequency (14x)",
        definition: "A fundamental physical property of matter that causes it to experience a force when placed in an electromagnetic field.",
        quote: "What if I told you the answers lie in something as simple as an electric charge and an electric field?",
        character: "Physics Instructor",
        chapter: "Electric Charges and Fields Workshop",
        culturalNote: "In daily life, 'charge' also refers to battery power or financial cost, but in academic physics it specifically designates electrostatic magnitude measured in Coulombs.",
        etymology: "From Old French 'charger' (to load), from Late Latin 'carricare' (to load a wagon); adapted to physics in the 18th century.",
        latexEquation: "$$q = n \cdot e \quad \text{where } e = 1.602 \times 10^{-19} \text{ C}$$",
        equation: "[The stronger] + [the charge], + [the stronger] + [the field]",
        synonyms: ["electric charge", "electrostatic quantity"],
        antonyms: ["neutrality"],
        hyponyms: ["positive charge", "negative charge", "point charge", "test charge"],
        hypernyms: ["physical property", "conserved quantity"],
        relatedWords: ["Coulomb", "electrostatics", "polarity", "field"],
        wordFamily: ["charge (Verb)", "charged (Adjective)", "rechargeable (Adjective)"],
        ontology: {
            domain: "Electromagnetism",
            subDomain: "Electrostatics",
            parentConcept: "Fundamental Property of Matter",
            childConcepts: ["Coulomb's Law", "Quantization of Charge"]
        }
    },
    {
        id: "vocab-2",
        term: "field",
        ipa: "/fiːld/",
        pos: "Noun",
        group: "Electric Field Theory • 🔥 Top High Frequency (11x)",
        definition: "A physical quantity associated with every point in space and time, specifically the invisible region of influence surrounding electric charges.",
        quote: "Imagine an invisible force field around any charged object—this is the electric field.",
        character: "Physics Instructor",
        chapter: "Electric Charges and Fields Workshop",
        culturalNote: "In English, Michael Faraday introduced the concept of 'lines of force' which evolved into our modern vector field theory.",
        etymology: "Old English 'feld' (open land); extended mathematically in the 19th century to denote a spatial distribution of a physical quantity.",
        latexEquation: "$$\\vec{E} = \\frac{\\vec{F}}{q_0} = \\frac{1}{4\\pi\\varepsilon_0} \\frac{q}{r^2} \\hat{r}$$",
        equation: "[The electric field] + [tells] + [other charges] + [how to move]",
        synonyms: ["force field", "vector field", "spatial region of influence"],
        antonyms: ["fieldless space", "vacuum void"],
        hyponyms: ["uniform field", "radial field", "dipole field"],
        hypernyms: ["physical continuum", "spatial vector distribution"],
        relatedWords: ["vector", "potential", "flux", "Faraday", "lines of force"],
        wordFamily: ["field (Adjective)", "fieldwork (Noun)"],
        ontology: {
            domain: "Electromagnetism",
            subDomain: "Field Theory",
            parentConcept: "Spatial Force Distribution",
            childConcepts: ["Electric Flux", "Gauss's Law"]
        }
    },
    {
        id: "vocab-3",
        term: "electricity",
        ipa: "/ɪˌlɛkˈtrɪs.ə.ti/",
        pos: "Noun",
        group: "Electrodynamics • 🔥 High Frequency (10x across electric/electricity)",
        definition: "A form of energy resulting from the existence of charged particles (such as electrons or protons), either statically as an accumulation of charge or dynamically as a current.",
        quote: "They power our world, from how electricity flows through wires to how lightning forms in a storm.",
        character: "Physics Instructor",
        chapter: "Electric Charges and Fields Workshop",
        culturalNote: "In both academic and everyday English, 'electricity' denotes the general energy phenomenon, while 'electric current' refers specifically to the rate of charge flow.",
        etymology: "From Latin 'electricus' (resembling amber), from Greek 'elektron' (amber), since rubbing amber produced static attraction.",
        latexEquation: "$$I = \\frac{dq}{dt}, \\quad P = V \\cdot I$$",
        equation: "[Electricity] + [flows through] + [wires] + [to power our world]",
        synonyms: ["electrical energy", "electric power", "current"],
        antonyms: [],
        hyponyms: ["static electricity", "current electricity", "hydroelectricity"],
        hypernyms: ["physical energy", "electromagnetic phenomenon"],
        relatedWords: ["electron", "current", "voltage", "conductor", "charge"],
        wordFamily: ["electric (Adjective)", "electrical (Adjective)", "electrify (Verb)"],
        ontology: {
            domain: "Physical Sciences",
            subDomain: "Electromagnetism",
            parentConcept: "Energy Form",
            childConcepts: ["Static Electricity", "Dynamic Current"]
        }
    },
    {
        id: "vocab-4",
        term: "electron",
        ipa: "/ɪˈlɛk.trɑːn/",
        pos: "Noun",
        group: "Atomic Structure • 🔥 High Frequency (4x)",
        definition: "A stable subatomic particle with a negative fundamental electric charge, found orbiting the nucleus of an atom or moving freely in conductors.",
        quote: "Protons carry a positive charge, while electrons carry a negative charge...",
        character: "Physics Instructor",
        chapter: "Electric Charges and Fields Workshop",
        culturalNote: "Native scientists often refer to 'free electrons' or the 'sea of electrons' when discussing electrical conductivity in metals.",
        etymology: "Coined in 1891 by George Johnstone Stoney from 'electric' + '-on' (particle suffix); ultimately from Greek 'elektron' (amber).",
        latexEquation: "$$Q_e = -1e = -1.602 \\times 10^{-19} \\text{ C}$$",
        equation: "[When] + [an object] + [gains or loses] + [electrons], + [it becomes electrically charged]",
        synonyms: ["negative subatomic particle", "beta particle"],
        antonyms: ["positron", "proton"],
        hyponyms: ["valence electron", "conduction electron", "core electron"],
        hypernyms: ["subatomic particle", "lepton", "fermion"],
        relatedWords: ["electricity", "orbit", "charge", "current", "amber"],
        wordFamily: ["electronic (Adjective)", "electronics (Noun)", "electronegativity (Noun)"],
        ontology: {
            domain: "Physical Sciences",
            subDomain: "Electromagnetism & Particle Physics",
            parentConcept: "Lepton",
            childConcepts: ["Spin", "Orbital Shells"]
        }
    },
    {
        id: "vocab-5",
        term: "pullover",
        ipa: "/ˈpʊlˌoʊ.vər/",
        pos: "Noun",
        group: "Everyday Materials • 🔥 High Frequency (3x)",
        definition: "A knitted garment worn over the upper body, typically put on by pulling it over the head, commonly used in physics demonstrations of triboelectric charging.",
        quote: "Rub that balloon on your pullover and bam—the balloon steals some electrons from your pullover...",
        character: "Physics Instructor",
        chapter: "Electric Charges and Fields Workshop",
        culturalNote: "In British English, 'jumper' or 'pullover' is used where American English often prefers 'sweater' or 'hoodie'.",
        etymology: "Compound noun formed in early 20th century from verb phrase 'pull over' (to pull over the head).",
        latexEquation: "$$\\Delta Q_{\\text{balloon}} = -\\Delta Q_{\\text{pullover}} \\implies Q_{\\text{total}} = \\text{const}$$",
        equation: "[Rub] + [that balloon] + [on your pullover]",
        synonyms: ["sweater", "jumper", "cardigan", "wool top"],
        antonyms: [],
        hyponyms: ["wool pullover", "fleece pullover"],
        hypernyms: ["clothing", "garment", "triboelectric material"],
        relatedWords: ["balloon", "friction", "wool", "static electricity", "triboelectric series"],
        wordFamily: ["pull (Verb)", "over (Preposition)"],
        ontology: {
            domain: "Everyday Materials",
            subDomain: "Triboelectric Materials",
            parentConcept: "Textile / Electron Donor",
            childConcepts: ["Static Cling"]
        }
    },
    {
        id: "vocab-6",
        term: "balloon",
        ipa: "/bəˈluːn/",
        pos: "Noun",
        group: "Triboelectric Materials • 🔥 High Frequency (3x)",
        definition: "A flexible, inflatable rubber bag used in physics classroom demonstrations to illustrate triboelectric charging and electrostatic induction when rubbed against hair or fabric.",
        quote: "Have you ever wondered why your hair stands up when you rub a balloon on your head... rub that balloon on your pullover and bam!",
        character: "Physics Instructor",
        chapter: "Electric Charges and Fields Workshop",
        culturalNote: "The rubbed balloon is the quintessential hook in American and British physics classrooms for demonstrating that everyday objects can acquire a net electric charge.",
        etymology: "From French 'ballon' (large ball), from Italian 'pallone'.",
        latexEquation: "$$F_e = q_{\\text{balloon}} E_{\\text{hair}} \\implies F_e > m g$$",
        equation: "[Rub] + [that balloon] + [on your pullover] + [->] + [Gains negative charge]",
        synonyms: ["inflatable sphere", "rubber membrane"],
        antonyms: [],
        hyponyms: ["rubber balloon", "latex balloon"],
        hypernyms: ["inflatable object", "dielectric insulator"],
        relatedWords: ["pullover", "rub", "triboelectricity", "static cling", "hair"],
        wordFamily: ["ballooning (Verb/Adjective)", "balloonist (Noun)"],
        ontology: {
            domain: "Pedagogical Demonstrations",
            subDomain: "Triboelectric Apparatus",
            parentConcept: "Dielectric Test Object",
            childConcepts: ["Charge Accumulation Surface"]
        }
    },
    {
        id: "vocab-7",
        term: "lightning",
        ipa: "/ˈlaɪt.nɪŋ/",
        pos: "Noun",
        group: "Atmospheric Physics • 🔥 High Frequency (3x)",
        definition: "A sudden electrostatic discharge during an electrical storm between electrically charged regions of a cloud, between clouds, or between a cloud and the ground.",
        quote: "Why lightning streaks across the sky during a storm... from how electricity flows through wires to how lightning forms in a storm.",
        character: "Physics Instructor",
        chapter: "Electric Charges and Fields Workshop",
        culturalNote: "Be careful not to confuse spelling with 'lightening' (making something lighter in weight or color). 'Lightning' is purely the natural electrical discharge.",
        etymology: "Late Middle English, from Old English 'leohting', derivative of 'leoht' (light).",
        latexEquation: "$$V_{\\text{breakdown}} \\approx 3 \\times 10^6 \\frac{\\text{V}}{\\text{m}} \\implies E \\cdot d > V_b$$",
        equation: "[Lightning] + [streaks across] + [the sky] + [during a storm]",
        synonyms: ["thunderbolt", "lightning bolt", "atmospheric discharge"],
        antonyms: [],
        hyponyms: ["cloud-to-ground lightning", "sheet lightning", "ball lightning"],
        hypernyms: ["electrostatic discharge", "atmospheric phenomenon"],
        relatedWords: ["thunder", "storm", "spark", "voltage breakdown", "plasma"],
        wordFamily: ["lightning-fast (Adjective)"],
        ontology: {
            domain: "Atmospheric Physics & Electromagnetism",
            subDomain: "High-Voltage Electrostatics",
            parentConcept: "Dielectric Breakdown",
            childConcepts: ["Stepped Leader", "Return Stroke"]
        }
    },
    {
        id: "vocab-8",
        term: "positive",
        ipa: "/ˈpɑː.zə.tɪv/",
        pos: "Adjective",
        group: "Charge Polarity • 🔥 High Frequency (3x)",
        definition: "Possessing an electric charge of the same polarity as a proton, resulting from a deficit of electrons relative to protons.",
        quote: "Protons carry a positive charge... giving your pullover a positive charge.",
        character: "Physics Instructor",
        chapter: "Electric Charges and Fields Workshop",
        culturalNote: "Assigned arbitrarily by Benjamin Franklin in the 18th century; by convention, electric field lines point AWAY from positive charges.",
        etymology: "From Latin 'positivus' (settled by agreement), from 'ponere' (to place). Applied to electricity by Benjamin Franklin in 1747.",
        latexEquation: "$$\\vec{E}(+q) \\propto +\\hat{r} \\quad (\\text{Vectors diverge outward})$$",
        equation: "[Field vectors] + [point away from] + [positive charges (+q)]",
        synonyms: ["plus charge", "anodic (in cells)"],
        antonyms: ["negative"],
        hyponyms: ["strongly positive", "net positive"],
        hypernyms: ["polar", "charged"],
        relatedWords: ["proton", "cation", "anode", "deficit", "polarity"],
        wordFamily: ["positively (Adverb)", "positivity (Noun)"],
        ontology: {
            domain: "Electromagnetism",
            subDomain: "Charge Polarity",
            parentConcept: "Electric Polarity State",
            childConcepts: ["Proton Polarity", "Cation Polarity"]
        }
    },
    {
        id: "vocab-9",
        term: "proton",
        ipa: "/ˈproʊ.tɑːn/",
        pos: "Noun",
        group: "Atomic Structure • Medium Frequency (2x)",
        definition: "A stable subatomic particle occurring in all atomic nuclei, bearing a positive electric charge equal in magnitude to that of an electron.",
        quote: "Every atom is made up of protons, neutrons, and electrons. Protons carry a positive charge...",
        character: "Physics Instructor",
        chapter: "Electric Charges and Fields Workshop",
        culturalNote: "In academic physics discussions, 'proton' is frequently used in contrast with 'electron' when describing charge imbalances in matter.",
        etymology: "From Greek 'proton' meaning 'first', coined by Ernest Rutherford in 1920 from the hydrogen nucleus.",
        latexEquation: "$$Q_p = +1e = +1.602 \\times 10^{-19} \\text{ C}$$",
        equation: "[Every atom] + [is made up of] + [protons, neutrons, and electrons]",
        synonyms: ["positive subatomic particle", "hydrogen nucleus"],
        antonyms: ["electron", "antiproton"],
        hyponyms: ["free proton", "bound proton"],
        hypernyms: ["subatomic particle", "nucleon", "hadron"],
        relatedWords: ["neutron", "nucleus", "atomic number", "positive charge"],
        wordFamily: ["protonic (Adjective)", "protonate (Verb)", "protonation (Noun)"],
        ontology: {
            domain: "Physical Sciences",
            subDomain: "Particle Physics",
            parentConcept: "Atomic Nucleus",
            childConcepts: ["Quarks", "Gluons"]
        }
    },
    {
        id: "vocab-10",
        term: "neutron",
        ipa: "/ˈnuː.trɑːn/",
        pos: "Noun",
        group: "Atomic Structure • Medium Frequency (2x)",
        definition: "A subatomic particle of about the same mass as a proton but without an electric charge, present in all atomic nuclei except those of ordinary hydrogen.",
        quote: "Protons carry a positive charge, while electrons carry a negative charge, and neutrons are neutral.",
        character: "Physics Instructor",
        chapter: "Electric Charges and Fields Workshop",
        culturalNote: "The word is a standard fixture in nuclear physics; students should note the pronunciation starts with /nuː/ or /njuː/ depending on American vs. British accent.",
        etymology: "From Latin 'neuter' (neither) + '-on' particle suffix; discovered and named by James Chadwick in 1932.",
        latexEquation: "$$Q_n = 0 \\text{ C} \\quad (m_n \\approx 1.675 \\times 10^{-27} \\text{ kg})$$",
        equation: "[Neutrons] + [are] + [neutral] + [within the nucleus]",
        synonyms: ["neutral nucleon"],
        antonyms: [],
        hyponyms: ["thermal neutron", "fast neutron"],
        hypernyms: ["subatomic particle", "nucleon", "baryon"],
        relatedWords: ["neutral", "nucleus", "isotope", "fission"],
        wordFamily: ["neutral (Adjective)", "neutralize (Verb)", "neutrality (Noun)"],
        ontology: {
            domain: "Physical Sciences",
            subDomain: "Nuclear Physics",
            parentConcept: "Nucleon",
            childConcepts: ["Isotope stability"]
        }
    },
    {
        id: "vocab-11",
        term: "negative",
        ipa: "/ˈnɛɡ.ə.tɪv/",
        pos: "Adjective",
        group: "Charge Polarity • Medium Frequency (2x)",
        definition: "Possessing an electric charge of the same polarity as an electron, resulting from a surplus of electrons relative to protons.",
        quote: "While electrons carry a negative charge, and neutrons are neutral.",
        character: "Physics Instructor",
        chapter: "Electric Charges and Fields Workshop",
        culturalNote: "By convention, electric field lines point TOWARD negative charges. Electrons are the primary mobile negative charges in everyday electronics.",
        etymology: "From Latin 'negativus' (that denies), from 'negare' (to deny). Applied to electricity by Benjamin Franklin.",
        latexEquation: "$$\\vec{E}(-q) \\propto -\\hat{r} \\quad (\\text{Vectors converge inward})$$",
        equation: "[Field vectors] + [point toward] + [negative charges (-q)]",
        synonyms: ["minus charge", "cathodic (in cells)"],
        antonyms: ["positive"],
        hyponyms: ["strongly negative", "net negative"],
        hypernyms: ["polar", "charged"],
        relatedWords: ["electron", "anion", "cathode", "surplus", "polarity"],
        wordFamily: ["negatively (Adverb)", "negativity (Noun)"],
        ontology: {
            domain: "Electromagnetism",
            subDomain: "Charge Polarity",
            parentConcept: "Electric Polarity State",
            childConcepts: ["Electron Polarity", "Anion Polarity"]
        }
    },
    {
        id: "vocab-12",
        term: "attract",
        ipa: "/əˈtrækt/",
        pos: "Verb",
        group: "Electrostatic Forces • Medium Frequency (2x)",
        definition: "To exert a physical pulling force that draws an object with opposite electric charge toward oneself.",
        quote: "Charged objects can attract or repel each other: Opposites attract and like charges repel.",
        character: "Physics Instructor",
        chapter: "Electric Charges and Fields Workshop",
        culturalNote: "Often paired with 'repel' as fundamental opposites. The proverb 'opposites attract' originated from electrostatics and magnetism before becoming a common idiom for relationships.",
        etymology: "From Latin 'attrahere' (to draw toward), from 'ad-' (to) + 'trahere' (to pull/draw).",
        latexEquation: "$$\\vec{F}_{12} = -k_e \\frac{|q_1 q_2|}{r_{12}^2} \\hat{r}_{12} \\quad (q_1 q_2 < 0)$$",
        equation: "[Opposite charges] + [attract] + [each other] + [with a force inversely proportional to distance squared]",
        synonyms: ["pull toward", "draw closer", "gravitate"],
        antonyms: ["repel", "push away", "deflect"],
        hyponyms: ["electrostatically attract", "magnetically attract"],
        hypernyms: ["exert force", "interact"],
        relatedWords: ["attraction", "attractive force", "Coulomb's Law", "opposite"],
        wordFamily: ["attraction (Noun)", "attractive (Adjective)", "attractively (Adverb)"],
        ontology: {
            domain: "Electromagnetism",
            subDomain: "Coulomb Interactions",
            parentConcept: "Vector Force Action",
            childConcepts: ["Attractive Electrostatic Vector"]
        }
    },
    {
        id: "vocab-13",
        term: "repel",
        ipa: "/rɪˈpɛl/",
        pos: "Verb",
        group: "Electrostatic Forces • Medium Frequency (2x)",
        definition: "To exert an outward physical force that pushes an object with identical (like) electric charge away from oneself.",
        quote: "Charged objects can attract or repel each other: Opposites attract and like charges repel.",
        character: "Physics Instructor",
        chapter: "Electric Charges and Fields Workshop",
        culturalNote: "In English pronunciation, stress the second syllable (/rɪˈpɛl/). The noun form changes slightly to 'repulsion'.",
        etymology: "From Latin 'repellere' (to drive back), from 're-' (back) + 'pellere' (to drive).",
        latexEquation: "$$\\vec{F}_{12} = +k_e \\frac{|q_1 q_2|}{r_{12}^2} \\hat{r}_{12} \\quad (q_1 q_2 > 0)$$",
        equation: "[Like charges] + [repel] + [each other] + [along the line joining their centers]",
        synonyms: ["push away", "drive back", "force outward"],
        antonyms: ["attract", "draw in"],
        hyponyms: ["electrostatically repel", "magnetically repel"],
        hypernyms: ["exert force", "interact"],
        relatedWords: ["repulsion", "repulsive force", "like charges", "deflection"],
        wordFamily: ["repulsion (Noun)", "repulsive (Adjective)", "repellency (Noun)"],
        ontology: {
            domain: "Electromagnetism",
            subDomain: "Coulomb Interactions",
            parentConcept: "Vector Force Action",
            childConcepts: ["Repulsive Electrostatic Vector"]
        }
    },
    {
        id: "vocab-14",
        term: "spark",
        ipa: "/spɑːrk/",
        pos: "Noun",
        group: "High-Voltage Phenomena • Medium Frequency (2x)",
        definition: "A momentary flash of light and sound accompanied by a sudden electrical discharge across an insulating gap when the electric field exceeds the dielectric strength of the medium.",
        quote: "This phenomenon is the spark behind it all... Let's keep the sparks flying!",
        character: "Physics Instructor",
        chapter: "Electric Charges and Fields Workshop",
        culturalNote: "Metaphorically, 'spark' means initial inspiration or excitement ('the spark behind it all'), but physically it denotes electrostatic breakdown in air.",
        etymology: "From Old English 'spearca' (glowing particle thrown off by fire or friction).",
        latexEquation: "$$E_{\\text{air}} \\ge 3.0 \\times 10^6 \\frac{\\text{V}}{\\text{m}} \\implies \\text{Dielectric Breakdown}$$",
        equation: "[Electric Field > 3E6 V/m] + [->] + [Spark discharge across air gap]",
        synonyms: ["micro-lightning", "electrical flash", "discharge arc"],
        antonyms: [],
        hyponyms: ["static spark", "ignition spark", "plasma channel"],
        hypernyms: ["electrostatic discharge", "plasma phenomenon"],
        relatedWords: ["lightning", "voltage breakdown", "air gap", "static zap", "phenomenon"],
        wordFamily: ["spark (Verb)", "sparkling (Adjective)", "sparky (Adjective)"],
        ontology: {
            domain: "Electromagnetism",
            subDomain: "Electrostatic Discharge",
            parentConcept: "Dielectric Breakdown",
            childConcepts: ["Micro-arc Formation", "Ozone Production"]
        }
    },
    {
        id: "vocab-15",
        term: "storm",
        ipa: "/stɔːrm/",
        pos: "Noun",
        group: "Atmospheric Physics • Medium Frequency (2x)",
        definition: "A severe atmospheric disturbance with strong winds, rain, and intense electrical activity characterized by charge separation within cumulonimbus clouds.",
        quote: "Why lightning streaks across the sky during a storm... from how electricity flows through wires to how lightning forms in a storm.",
        character: "Physics Instructor",
        chapter: "Electric Charges and Fields Workshop",
        culturalNote: "In atmospheric electricity, 'thunderstorm' specifically implies that vertical air currents have separated ice particles into positive and negative regions.",
        etymology: "From Old English 'storm' (tempest/violent weather), common to Germanic languages.",
        latexEquation: "$$V_{\\text{top}} - V_{\\text{bottom}} \\approx 10^8 \\text{ V} \\implies \\text{Charge Separation}$$",
        equation: "[Updraft friction in storm cloud] + [->] + [Charge separation (+ top, - bottom)]",
        synonyms: ["tempest", "thunderstorm", "electrical tempest"],
        antonyms: ["calm", "fair weather"],
        hyponyms: ["supercell storm", "electrical storm", "thunderstorm"],
        hypernyms: ["meteorological disturbance", "atmospheric condition"],
        relatedWords: ["lightning", "thunder", "cloud", "updraft", "charge separation"],
        wordFamily: ["stormy (Adjective)", "storming (Verb)"],
        ontology: {
            domain: "Atmospheric Physics",
            subDomain: "Storm Electrification",
            parentConcept: "Weather System",
            childConcepts: ["Cloud-to-Ground Discharge", "Intra-cloud Lightning"]
        }
    },

    // --- ESSENTIAL DISCOURSE CONNECTORS (`Los conectores que más salen`) ---
    {
        id: "vocab-16",
        term: "while",
        ipa: "/waɪl/",
        pos: "Connector",
        group: "Discourse Markers • 🟡 Connector (Contrast)",
        definition: "A subordinating conjunction used here to express simultaneous contrast between two different facts or properties.",
        quote: "Protons carry a positive charge, while electrons carry a negative charge, and neutrons are neutral.",
        character: "Physics Instructor",
        chapter: "Electric Charges and Fields Workshop",
        culturalNote: "When comparing technical concepts in CLIL/EMI, 'while' and 'whereas' are the most elegant connectors to show direct contrast in a single sentence.",
        etymology: "From Old English 'hwīl' (period of time); evolved to indicate simultaneous temporal duration and logical contrast.",
        latexEquation: "$$\\text{Clause}_A (+q) \\iff \\text{while} \\iff \\text{Clause}_B (-q)$$",
        equation: "[Clause A: Protons are positive], + [while] + [Clause B: electrons are negative]",
        synonyms: ["whereas", "on the other hand", "whilst"],
        antonyms: ["similarly", "likewise"],
        hyponyms: [],
        hypernyms: ["conjunction", "contrastive connector"],
        relatedWords: ["contrast", "comparison", "whereas", "however"],
        wordFamily: ["meanwhile (Adverb)"],
        ontology: {
            domain: "Academic Discourse",
            subDomain: "Logical Contrast",
            parentConcept: "Subordinating Conjunction",
            childConcepts: ["Direct Comparison Structure"]
        }
    },
    {
        id: "vocab-17",
        term: "for example",
        ipa: "/fər ɪɡˈzæm.pəl/",
        pos: "Connector",
        group: "Discourse Markers • 🟡 Connector (Exemplification)",
        definition: "A transitional phrase used to introduce a specific concrete illustration of a general principle just stated.",
        quote: "When an object gains or loses electrons, it becomes electrically charged. For example, rub that balloon on your pullover and bam...",
        character: "Physics Instructor",
        chapter: "Electric Charges and Fields Workshop",
        culturalNote: "In academic writing, often abbreviated as 'e.g.' (Latin 'exempli gratia'). In oral presentations, saying 'For example' provides a clear cue that a practical demonstration is next.",
        etymology: "From Latin 'pro exemplum'; 'example' from Latin 'exemplum' (sample/pattern).",
        latexEquation: "$$\\forall q \\in \\text{Matter}, \\quad q = ne \\implies \\text{e.g., rub balloon}$$",
        equation: "[General Principle] + [.] + [For example,] + [Concrete Demonstration]",
        synonyms: ["for instance", "to illustrate", "as an illustration", "e.g."],
        antonyms: [],
        hyponyms: [],
        hypernyms: ["exemplifying transition"],
        relatedWords: ["illustration", "demonstration", "case study"],
        wordFamily: ["exemplify (Verb)", "exemplary (Adjective)"],
        ontology: {
            domain: "Academic Discourse",
            subDomain: "Exemplification",
            parentConcept: "Discourse Connector",
            childConcepts: ["Empirical Illustration"]
        }
    },
    {
        id: "vocab-18",
        term: "think of it like",
        ipa: "/θɪŋk əv ɪt laɪk/",
        pos: "Phrasal Verb / Connector",
        group: "Discourse Markers • 🟡 Connector (Analogy)",
        definition: "A pedagogical discourse chunk used to introduce an intuitive analogy or mental model for an abstract scientific concept.",
        quote: "It tells other charges how to move. Think of it like a map for charges to follow.",
        character: "Physics Instructor",
        chapter: "Electric Charges and Fields Workshop",
        culturalNote: "Native science communicators rely heavily on 'Think of it like...' or 'Imagine...' to bridge abstract mathematical physics with familiar real-world experiences.",
        etymology: "Modern conversational idiom combining 'think of' (contemplate/conceptualize) with preposition 'like' (similar to).",
        latexEquation: "$$\\vec{E}(\\vec{r}) \\equiv \\text{Spatial Vector Map} \\ \\vec{F}(\\vec{r})$$",
        equation: "[Abstract Concept: Electric Field] + [->] + [Think of it like] + [Concrete Analogy: A Map]",
        synonyms: ["imagine it as", "visualize it as", "compare it to", "picture it like"],
        antonyms: [],
        hyponyms: [],
        hypernyms: ["analogical prompt", "pedagogical framing"],
        relatedWords: ["analogy", "metaphor", "mental model", "visualization"],
        wordFamily: ["thought of (Past)"],
        ontology: {
            domain: "Pedagogical Communication",
            subDomain: "Analogical Reasoning",
            parentConcept: "Explanatory Framing",
            childConcepts: ["Mental Model Bridging"]
        }
    },
    {
        id: "vocab-19",
        term: "when",
        ipa: "/wɛn/",
        pos: "Connector",
        group: "Discourse Markers • 🟡 Connector (Conditional/Temporal 2x)",
        definition: "A subordinating conjunction introducing a necessary physical condition, time threshold, or trigger event that leads to a scientific outcome.",
        quote: "Have you ever wondered why your hair stands up when you rub a balloon on your head... When an object gains or loses electrons, it becomes electrically charged.",
        character: "Physics Instructor",
        chapter: "Electric Charges and Fields Workshop",
        culturalNote: "In scientific definitions and laws, 'when' operates as a logical trigger equivalent to 'under the condition that' ('When X happens, Y follows').",
        etymology: "From Old English 'hwænne' (at what time/whenever), Proto-Germanic 'hwan'.",
        latexEquation: "$$\\text{Condition: } \\Delta q \\neq 0 \\implies \\text{Object is charged}$$",
        equation: "[When] + [Condition: object gains/loses electrons], + [Outcome: it becomes charged]",
        synonyms: ["whenever", "at the moment that", "under the condition that", "once"],
        antonyms: ["never"],
        hyponyms: [],
        hypernyms: ["conditional conjunction", "temporal transition"],
        relatedWords: ["condition", "trigger", "if", "whenever", "outcome"],
        wordFamily: ["whence (Adverb)"],
        ontology: {
            domain: "Academic Discourse",
            subDomain: "Logical Causation",
            parentConcept: "Subordinating Conjunction",
            childConcepts: ["Conditional Physics Trigger"]
        }
    },
    {
        id: "vocab-20",
        term: "because",
        ipa: "/bɪˈkɔːz/",
        pos: "Connector",
        group: "Discourse Markers • 🟡 Connector (Causation)",
        definition: "A subordinating conjunction used to introduce the direct scientific reasoning, causal explanation, or motivation behind a physical statement.",
        quote: "Stick around, because in the next 2 minutes we're diving into the electrifying world of physics!",
        character: "Physics Instructor",
        chapter: "Electric Charges and Fields Workshop",
        culturalNote: "In formal scientific writing, 'because' introduces an unambiguous causal subordinate clause explaining 'why' a phenomenon occurs.",
        etymology: "Middle English, from preposition 'by' + noun 'cause' (from Latin 'causa').",
        latexEquation: "$$\\text{Cause: } \\vec{E} \\text{ field exists} \\implies \\text{Effect: } \\vec{F} = q\\vec{E}$$",
        equation: "[Main Action/Effect] + [because] + [Causal Explanation / Reason]",
        synonyms: ["since", "as", "due to the fact that", "for the reason that"],
        antonyms: ["despite", "although"],
        hyponyms: [],
        hypernyms: ["causal conjunction", "explanatory marker"],
        relatedWords: ["cause", "reason", "explanation", "consequence", "therefore"],
        wordFamily: ["cause (Noun/Verb)"],
        ontology: {
            domain: "Academic Discourse",
            subDomain: "Scientific Causality",
            parentConcept: "Subordinating Conjunction",
            childConcepts: ["Direct Causal Link"]
        }
    },
    {
        id: "vocab-21",
        term: "now",
        ipa: "/naʊ/",
        pos: "Connector",
        group: "Discourse Markers • 🟡 Connector (Topic Transition)",
        definition: "A conversational discourse transition marker used by lecturers to signal the completion of one topic and the immediate start of a new focus area.",
        quote: "Now let's talk about the electric field. Imagine an invisible force field around any charged object...",
        character: "Physics Instructor",
        chapter: "Electric Charges and Fields Workshop",
        culturalNote: "When a professor says 'Now...' with a slight pause, native students immediately recognize a major transition between sections of a lecture.",
        etymology: "From Old English 'nū' (at the present time/immediate transition), Proto-Indo-European '*nu'.",
        latexEquation: "$$t_0 \\to t_1: \\text{Transition from } Q \\text{ to E-field}$$",
        equation: "[End of Topic A: Electric Charge] + [.] + [Now] + [Start Topic B: Electric Field]",
        synonyms: ["next", "at this point", "moving forward", "let us turn to"],
        antonyms: ["previously", "earlier"],
        hyponyms: [],
        hypernyms: ["discourse signpost", "transitional marker"],
        relatedWords: ["transition", "signpost", "next", "topic shift"],
        wordFamily: ["nowadays (Adverb)"],
        ontology: {
            domain: "Pedagogical Communication",
            subDomain: "Lecture Structure",
            parentConcept: "Discourse Transition Marker",
            childConcepts: ["Topic Shift Signpost"]
        }
    },
    {
        id: "vocab-22",
        term: "so",
        ipa: "/soʊ/",
        pos: "Connector",
        group: "Discourse Markers • 🟡 Connector (Summary / Conclusion)",
        definition: "A coordinating conjunction or discourse marker used at the conclusion of a scientific explanation to synthesize practical takeaways or state logical consequences.",
        quote: "So the next time you feel that static zap or see a lightning bolt, you'll know it's all about electric charges and fields at work!",
        character: "Physics Instructor",
        chapter: "Electric Charges and Fields Workshop",
        culturalNote: "In STEM lectures, starting a summary sentence with 'So...' gathers all preceding theoretical points into an actionable real-world conclusion.",
        etymology: "From Old English 'swā' (in this way/to such an extent), common Germanic root.",
        latexEquation: "$$\\sum \\vec{F} = q\\vec{E} \\implies \\therefore \\text{⚡ Lightning & Static Zap}$$",
        equation: "[Theoretical Explanation] + [->] + [So,] + [Real-World Takeaway / Synthesis]",
        synonyms: ["therefore", "consequently", "as a result", "thus", "in conclusion"],
        antonyms: ["however", "nevertheless"],
        hyponyms: [],
        hypernyms: ["conclusive connector", "synthesizing marker"],
        relatedWords: ["conclusion", "consequence", "therefore", "summary", "result"],
        wordFamily: ["so-called (Adjective)"],
        ontology: {
            domain: "Academic Discourse",
            subDomain: "Logical Synthesis",
            parentConcept: "Coordinating Conjunction",
            childConcepts: ["Conclusive Takeaway Marker"]
        }
    },
    {
        id: "vocab-23",
        term: "here's the cool part",
        ipa: "/hɪrz ðə kuːl pɑːrt/",
        pos: "Connector",
        group: "Discourse Markers • 🟡 Discourse Chunk (Hook Focus)",
        definition: "A high-engagement pedagogical idiom used by lecturers to grab student attention right before introducing a surprising or universal scientific implication.",
        quote: "And here's the cool part: electric fields are everywhere! They govern how charges interact across space.",
        character: "Physics Instructor",
        chapter: "Electric Charges and Fields Workshop",
        culturalNote: "This casual conversational signpost lowers cognitive anxiety and sparks curiosity right before delivering abstract conceptual laws.",
        etymology: "Modern American English classroom idiom combining adverbial focus 'here is' with informal appreciation 'the cool part'.",
        latexEquation: "$$\\vec{E}_{\\text{universal}} \\in \\mathbb{R}^3 \\implies \\text{Governs all space}$$",
        equation: "[Basic Physics Principle] + [->] + [And here's the cool part:] + [Universal Real-World Application]",
        synonyms: ["what is fascinating is", "interestingly enough", "remarkably", "the exciting part is"],
        antonyms: ["mundanely", "unsurprisingly"],
        hyponyms: [],
        hypernyms: ["attitudinal discourse marker", "pedagogical hook"],
        relatedWords: ["fascinating", "universal", "attention-grabber", "curiosity"],
        wordFamily: ["cool (Adjective)"],
        ontology: {
            domain: "Pedagogical Communication",
            subDomain: "Student Engagement Strategies",
            parentConcept: "Discourse Signpost",
            childConcepts: ["Affective Attention Hook"]
        }
    },

    // --- LOW-FREQUENCY / RARE ACADEMIC TERMS (`Las palabras que menos salen - 1 occurrence`) ---
    {
        id: "vocab-24",
        term: "invisible",
        ipa: "/ɪnˈvɪz.ə.bəl/",
        pos: "Adjective",
        group: "Electric Field Theory • 💎 Low Frequency (1x - Rare Term)",
        definition: "Unable to be perceived by the human eye, requiring mathematical vectors or field lines to visualize its physical effects across space.",
        quote: "Imagine an invisible force field around any charged object—this is the electric field.",
        character: "Physics Instructor",
        chapter: "Electric Charges and Fields Workshop",
        culturalNote: "Because fields E and B are physically real yet invisible, physics relies heavily on interactive simulators with vector grids to make them tangible.",
        etymology: "From Latin 'invisibilis', from 'in-' (not) + 'visibilis' (visible), from 'videre' (to see).",
        latexEquation: "$$\\vec{E}(x,y,z) = -\\nabla V(x,y,z) \\quad (\\text{Non-optical field})$$",
        equation: "[Imagine] + [an invisible force field] + [around any charged object]",
        synonyms: ["unseen", "imperceptible", "hidden"],
        antonyms: ["visible", "tangible", "observable"],
        hyponyms: [],
        hypernyms: ["imperceptible property"],
        relatedWords: ["force field", "vector", "visualization", "lines of force"],
        wordFamily: ["invisibility (Noun)", "invisibly (Adverb)"],
        ontology: {
            domain: "Physics Visualization",
            subDomain: "Sensory Perception in Physics",
            parentConcept: "Non-Optical Physical Quantity",
            childConcepts: ["Field Representation"]
        }
    },
    {
        id: "vocab-25",
        term: "govern",
        ipa: "/ˈɡʌv.ɚn/",
        pos: "Verb",
        group: "Physical Laws • 💎 Low Frequency (1x - Rare Term)",
        definition: "To directly control, dictate the behavior of, or serve as the underlying physical law regulating how physical entities interact.",
        quote: "And here's the cool part: electric fields are everywhere! They govern how charges interact across space.",
        character: "Physics Instructor",
        chapter: "Electric Charges and Fields Workshop",
        culturalNote: "In formal scientific discourse, 'govern' and 'dictate' express how fundamental physical laws regulate natural phenomena without exception.",
        etymology: "From Old French 'governer', from Latin 'gubernare' (to steer a ship), from Greek 'kybernain'.",
        latexEquation: "$$\\nabla \\cdot \\vec{E} = \\frac{\\rho}{\\varepsilon_0}, \\quad \\nabla \\times \\vec{E} = -\\frac{\\partial \\vec{B}}{\\partial t}$$",
        equation: "[Electric fields] + [govern] + [how charges interact] + [across space]",
        synonyms: ["rule", "dictate", "regulate", "control", "determine"],
        antonyms: [],
        hyponyms: ["mathematically govern", "physically rule"],
        hypernyms: ["regulate", "influence"],
        relatedWords: ["governing equation", "physical law", "Maxwell's Equations", "interaction"],
        wordFamily: ["governing (Adjective)", "governance (Noun)", "governor (Noun)"],
        ontology: {
            domain: "Theoretical Physics",
            subDomain: "Physical Laws & Axioms",
            parentConcept: "Law of Nature",
            childConcepts: ["Maxwell's Governing Equations"]
        }
    },
    {
        id: "vocab-26",
        term: "phenomenon",
        ipa: "/fəˈnɑː.mə.nɑːn/",
        pos: "Noun",
        group: "Academic Physics • 💎 Low Frequency (1x - Rare Term)",
        definition: "An observable physical event, fact, or occurrence whose cause or explanation is a subject of scientific investigation.",
        quote: "This phenomenon is the spark behind it all.",
        character: "Physics Instructor",
        chapter: "Electric Charges and Fields Workshop",
        culturalNote: "Be very careful with plural vs. singular: one 'phenomenon', multiple 'phenomena'. Using 'phenomenons' is considered a grammatical error in scientific English.",
        etymology: "From Late Latin 'phenomenon', from Greek 'phainomenon' (that which is seen/appears), from 'phainesthai' (to appear).",
        latexEquation: "$$\\Delta V_{\\text{cloud-ground}} > V_{\\text{crit}} \\implies \\text{Spark channel}$$",
        equation: "[Observable physical event] + [=] + [A scientific phenomenon (singular)]",
        synonyms: ["occurrence", "observable event", "physical manifestation", "happening"],
        antonyms: ["unobservable abstraction", "non-event"],
        hyponyms: ["electrostatic phenomenon", "optical phenomenon", "atmospheric phenomenon"],
        hypernyms: ["physical reality", "empirical fact"],
        relatedWords: ["phenomena (Plural)", "observation", "empirical", "manifestation"],
        wordFamily: ["phenomena (Plural Noun)", "phenomenal (Adjective)", "phenomenology (Noun)"],
        ontology: {
            domain: "Scientific Methodology & Epistemology",
            subDomain: "Empirical Observation",
            parentConcept: "Observable Entity",
            childConcepts: ["Electromagnetic Phenomenon"]
        }
    },
    {
        id: "vocab-27",
        term: "streaks",
        ipa: "/striːks/",
        pos: "Verb",
        group: "Atmospheric Physics • 💎 Low Frequency (1x - Rare Term)",
        definition: "To move across a region of space at extremely high speed, leaving a visible linear trace or glowing path of light behind.",
        quote: "Have you ever wondered why your hair stands up when you rub a balloon on your head, or why lightning streaks across the sky during a storm?",
        character: "Physics Instructor",
        chapter: "Electric Charges and Fields Workshop",
        culturalNote: "In descriptive physics and meteorology, saying lightning 'streaks' captures both the immense velocity (~100,000 km/s for return stroke) and the jagged illuminated plasma channel.",
        etymology: "From Old English 'strica' (line/stroke), related to 'strike' and Germanic root meaning a quick motion or line.",
        latexEquation: "$$v_{\\text{return\\_stroke}} \\approx \\frac{1}{3}c \\approx 1.0 \\times 10^8 \\frac{\\text{m}}{\\text{s}}$$",
        equation: "[High-voltage discharge] + [streaks across] + [the sky] + [at 100,000 km/s]",
        synonyms: ["flashes rapidly", "darts", "zooms", "blazes along"],
        antonyms: ["crawls", "meanders slowly", "stagnates"],
        hyponyms: ["streaks diagonally", "streaks vertically"],
        hypernyms: ["move rapidly", "propagate with light"],
        relatedWords: ["streak (Noun)", "lightning", "velocity", "plasma channel", "flash"],
        wordFamily: ["streak (Noun)", "streaking (Gerund/Participle)", "streaked (Past)"],
        ontology: {
            domain: "Kinematics & Atmospheric Physics",
            subDomain: "High-Speed Motion",
            parentConcept: "Rapid Propagation",
            childConcepts: ["Visual Trajectory Trace"]
        }
    },
    {
        id: "vocab-28",
        term: "gains",
        ipa: "/ɡeɪnz/",
        pos: "Verb",
        group: "Atomic Structure • 💎 Low Frequency (1x - Rare Term)",
        definition: "To acquire, absorb, or take in additional subatomic particles (such as electrons), thereby altering the net electrical charge of an atom or object.",
        quote: "When an object gains or loses electrons, it becomes electrically charged.",
        character: "Physics Instructor",
        chapter: "Electric Charges and Fields Workshop",
        culturalNote: "In chemistry and electrostatics, when a neutral atom 'gains' electrons, it becomes a negatively charged anion because electrons have a negative polarity.",
        etymology: "From Old French 'gaaignier' (to earn/cultivate), of Germanic origin.",
        latexEquation: "$$A^0 + n e^- \\longrightarrow A^{n-} \\quad (\\text{Anion formation})$$",
        equation: "[Neutral Atom] + [gains n electrons (-)] + [->] + [Anion with charge -ne]",
        synonyms: ["acquires", "absorbs", "takes on", "captures"],
        antonyms: ["loses", "donates", "sheds", "emits"],
        hyponyms: ["gains valence electrons", "gains thermal energy"],
        hypernyms: ["acquire", "change state"],
        relatedWords: ["loses", "electron", "anion", "net charge", "reduction"],
        wordFamily: ["gain (Noun/Verb)", "gained (Past)", "gaining (Gerund)"],
        ontology: {
            domain: "Electrostatics & Atomic Chemistry",
            subDomain: "Charge Acquisition",
            parentConcept: "Particle Transfer",
            childConcepts: ["Anion Formation", "Reduction Reaction"]
        }
    },
    {
        id: "vocab-29",
        term: "loses",
        ipa: "/ˈluː.zɪz/",
        pos: "Verb",
        group: "Atomic Structure • 💎 Low Frequency (1x - Rare Term)",
        definition: "To shed, donate, or give up subatomic particles (such as electrons) to another material, resulting in a net deficit of negative charge.",
        quote: "When an object gains or loses electrons, it becomes electrically charged.",
        character: "Physics Instructor",
        chapter: "Electric Charges and Fields Workshop",
        culturalNote: "In English spelling, take special care: 'loses' with one 'o' is the verb (to shed or misplace), whereas 'loose' with two 'o's is the adjective (not tight).",
        etymology: "From Old English 'losian' (to perish/destroy), influenced by 'lēosan' (to lose).",
        latexEquation: "$$B^0 - n e^- \\longrightarrow B^{n+} \\quad (\\text{Cation formation})$$",
        equation: "[Neutral Atom] + [loses n electrons (-)] + [->] + [Cation with charge +ne]",
        synonyms: ["sheds", "donates", "gives up", "releases"],
        antonyms: ["gains", "acquires", "absorbs"],
        hyponyms: ["loses outer electrons", "loses energy"],
        hypernyms: ["transfer away", "change state"],
        relatedWords: ["gains", "electron", "cation", "net charge", "oxidation"],
        wordFamily: ["lose (Verb base)", "lost (Past)", "loss (Noun)", "loser (Noun)"],
        ontology: {
            domain: "Electrostatics & Atomic Chemistry",
            subDomain: "Charge Donation",
            parentConcept: "Particle Transfer",
            childConcepts: ["Cation Formation", "Oxidation Reaction"]
        }
    },
    {
        id: "vocab-30",
        term: "interact",
        ipa: "/ˌɪn.təˈrækt/",
        pos: "Verb",
        group: "Electric Field Theory • 💎 Low Frequency (1x - Rare Term)",
        definition: "To act mutually upon each other, as when charged particles exert electrostatic forces of attraction or repulsion across a distance mediated by their electric fields.",
        quote: "And here's the cool part: electric fields are everywhere! They govern how charges interact across space.",
        character: "Physics Instructor",
        chapter: "Electric Charges and Fields Workshop",
        culturalNote: "In modern physics, forces do not act instantaneously at a distance without an intermediary; rather, charges 'interact' locally with the surrounding field.",
        etymology: "Formed in the 18th century from prefix 'inter-' (between/among) + verb 'act' (from Latin 'agere').",
        latexEquation: "$$U_{12} = k_e \\frac{q_1 q_2}{r_{12}} \\quad (\\text{Potential interaction energy})$$",
        equation: "[Charge q1] + [and Charge q2] + [interact] + [via their electric fields E1 and E2]",
        synonyms: ["act upon each other", "exert mutual force", "reciprocate"],
        antonyms: ["isolate", "remain inert"],
        hyponyms: ["electrostatically interact", "gravitationally interact"],
        hypernyms: ["exert physical influence", "behave mutually"],
        relatedWords: ["interaction", "Coulomb's Law", "force", "field", "mutual"],
        wordFamily: ["interaction (Noun)", "interactive (Adjective)", "interactivity (Noun)"],
        ontology: {
            domain: "Electromagnetism",
            subDomain: "Field Interactions",
            parentConcept: "Physical Action",
            childConcepts: ["Mutual Electrostatic Force"]
        }
    },
    {
        id: "vocab-31",
        term: "neutral",
        ipa: "/ˈnuː.trəl/",
        pos: "Adjective",
        group: "Charge Polarity • 💎 Low Frequency (1x - Rare Term)",
        definition: "Having no net electrical charge, either because an object possesses exactly equal numbers of protons and electrons, or because a particle (like a neutron) inherently has zero charge.",
        quote: "Protons carry a positive charge, while electrons carry a negative charge, and neutrons are neutral.",
        character: "Physics Instructor",
        chapter: "Electric Charges and Fields Workshop",
        culturalNote: "A 'neutral' macroscopic object is not empty of charge; rather, it contains billions of protons and electrons balanced in exact 1:1 mathematical equilibrium.",
        etymology: "From Middle French 'neutre', from Latin 'neutralis', from 'neuter' (neither one nor the other).",
        latexEquation: "$$\\sum_{i} q_i = N_p (+e) + N_e (-e) = 0 \\iff N_p = N_e$$",
        equation: "[Net Charge Q] + [= 0] + [when # of Protons (+) == # of Electrons (-)]",
        synonyms: ["uncharged", "equilibrated", "zero-charge"],
        antonyms: ["charged", "polar", "positive", "negative"],
        hyponyms: ["inherently neutral (neutron)", "macroscopically neutral (balanced atom)"],
        hypernyms: ["electric state", "balanced condition"],
        relatedWords: ["neutron", "neutralize", "equilibrium", "zero charge", "balance"],
        wordFamily: ["neutrality (Noun)", "neutralize (Verb)", "neutralization (Noun)"],
        ontology: {
            domain: "Electromagnetism",
            subDomain: "Charge Equilibrium",
            parentConcept: "Electric State",
            childConcepts: ["Neutron State", "Balanced Atomic State"]
        }
    },
    {
        id: "vocab-32",
        term: "static zap",
        ipa: "/ˈstæt.ɪk zæp/",
        pos: "Noun Phrase",
        group: "Everyday Phenomena • 💎 Low Frequency (1x - Rare Term)",
        definition: "A sudden, mild electric shock experienced by a person when accumulated static electricity discharges from their fingertips to a grounded metal object like a doorknob.",
        quote: "So the next time you feel that static zap or see a lightning bolt, you'll know it's all about electric charges and fields at work!",
        character: "Physics Instructor",
        chapter: "Electric Charges and Fields Workshop",
        culturalNote: "In everyday English, 'zap' is onomatopoeic slang for a sudden electrical spark or shock. Pairing it with 'static' makes electrostatic discharge relatable to daily life.",
        etymology: "Compound of 'static' (from Greek 'statikos' causing to stand) and 'zap' (mid-20th century imitative sound of electrical discharge).",
        latexEquation: "$$W = \\int \\vec{F} \\cdot d\\vec{l} = \\frac{1}{2} C V^2 \\implies \\text{Discharge spark}$$",
        equation: "[Finger at high potential V] + [approaches grounded metal V=0] + [->] + [Static Zap!]",
        synonyms: ["static shock", "electrostatic discharge", "electric prick", "mini-spark"],
        antonyms: [],
        hyponyms: ["doorknob zap", "car door shock"],
        hypernyms: ["electrostatic discharge", "sensory shock"],
        relatedWords: ["static electricity", "spark", "triboelectricity", "grounding", "voltage"],
        wordFamily: ["zap (Verb/Noun)", "zapped (Past)"],
        ontology: {
            domain: "Everyday Electrostatics",
            subDomain: "Human Sensory Discharge",
            parentConcept: "Electrostatic Discharge",
            childConcepts: ["Contact Spark Sensation"]
        }
    },
    {
        id: "vocab-33",
        term: "map",
        ipa: "/mæp/",
        pos: "Noun",
        group: "Electric Field Theory • 💎 Low Frequency (1x - Rare Term)",
        definition: "A visual representation or diagrammatic guide showing the direction and strength of forces or vectors across space.",
        quote: "Think of it like a map for charges to follow. The direction of the field? Easy: it points away from positive charges...",
        character: "Physics Instructor",
        chapter: "Electric Charges and Fields Workshop",
        culturalNote: "Metaphorically used in academic lectures to simplify complex vector fields so learners can intuitively trace force vectors.",
        etymology: "From Medieval Latin 'mappa mundi' (map of the world), from Latin 'mappa' (napkin/cloth).",
        latexEquation: "$$\\Phi_E = \\iint \\vec{E} \\cdot d\\vec{A} = \\frac{Q_{\\text{enc}}}{\\varepsilon_0}$$",
        equation: "[Think of] + [it] + [like a map] + [for charges to follow]",
        synonyms: ["chart", "diagram", "vector guide", "layout"],
        antonyms: [],
        hyponyms: ["vector map", "contour map", "equipotential map"],
        hypernyms: ["representation", "visualization"],
        relatedWords: ["direction", "lines of force", "vector", "compass"],
        wordFamily: ["map (Verb)", "mapping (Noun)", "mapped (Adjective)"],
        ontology: {
            domain: "Mathematical Physics",
            subDomain: "Vector Visualizations",
            parentConcept: "Spatial Representation",
            childConcepts: ["Field Lines", "Streamlines"]
        }
    },
    {
        id: "vocab-34",
        term: "steal",
        ipa: "/stiːl/",
        pos: "Verb",
        group: "Contact Electrification • 💎 Low Frequency (1x - Rare Term)",
        definition: "To strip or transfer electrons away from another material via friction due to higher electron affinity in triboelectric charging.",
        quote: "Rub that balloon on your pullover and bam—the balloon steals some electrons from your pullover, giving your pullover a positive charge.",
        character: "Physics Instructor",
        chapter: "Electric Charges and Fields Workshop",
        culturalNote: "Using 'steal' is a vivid pedagogical personification; technically, electrons are transferred because the balloon's rubber has a stronger electron affinity than wool/cotton.",
        etymology: "From Old English 'stelan' (to take unlawfully); used metaphorically in science education to make particle transfer memorable.",
        latexEquation: "$$\\chi_{\\text{rubber}} > \\chi_{\\text{wool}} \\implies e^- \\text{ transfer to rubber}$$",
        equation: "[The balloon] + [steals] + [electrons] + [from your pullover]",
        synonyms: ["strip", "extract", "transfer", "absorb"],
        antonyms: ["donate", "give", "yield"],
        hyponyms: ["triboelectrically strip"],
        hypernyms: ["transfer", "acquire"],
        relatedWords: ["affinity", "friction", "triboelectric series", "electron transfer"],
        wordFamily: ["stole (Past)", "stolen (Past Participle)", "stealing (Gerund)"],
        ontology: {
            domain: "Electrostatics",
            subDomain: "Contact Electrification",
            parentConcept: "Electron Transfer",
            childConcepts: ["Triboelectric Charging"]
        }
    },
    {
        id: "vocab-35",
        term: "flow",
        ipa: "/floʊ/",
        pos: "Verb",
        group: "Electrodynamics • 💎 Low Frequency (1x - Rare Term)",
        definition: "To move in a continuous, steady stream through a conductive medium under the influence of an electric potential difference.",
        quote: "They power our world, from how electricity flows through wires to how lightning forms in a storm.",
        character: "Physics Instructor",
        chapter: "Electric Charges and Fields Workshop",
        culturalNote: "We speak of electric current 'flowing' through a conductor exactly like water flowing through a pipe (the fluid analogy of electricity).",
        etymology: "From Old English 'flōwan' (to stream/issue); applied to electrical currents since Benjamin Franklin's one-fluid theory.",
        latexEquation: "$$\\vec{J} = \\sigma \\vec{E} = n e \\vec{v}_d$$",
        equation: "[Electricity] + [flows through] + [conductive wires] + [under a voltage difference]",
        synonyms: ["stream", "circulate", "conduct", "traverse"],
        antonyms: ["stagnate", "block", "insulate"],
        hyponyms: ["drift", "surge"],
        hypernyms: ["move", "propagate"],
        relatedWords: ["current", "wire", "conductor", "ampere", "drift velocity"],
        wordFamily: ["flow (Noun)", "flowing (Adjective)"],
        ontology: {
            domain: "Electrodynamics",
            subDomain: "Electric Current",
            parentConcept: "Charge Transport",
            childConcepts: ["Ohm's Law", "Drift Current"]
        }
    }
];

const MICROTEACHING_TRANSCRIPT = [
    { time: "0:00", text: "Have you ever wondered why your hair stands up when you rub a balloon on your head, or why lightning streaks across the sky during a storm?", highlightWords: ["wondered", "hair", "balloon", "lightning", "streaks", "storm", "rub", "when"] },
    { time: "0:08", text: "What if I told you the answers lie in something as simple as an electric charge and an electric field?", highlightWords: ["charge", "field"] },
    { time: "0:13", text: "Stick around, because in the next 2 minutes we're diving into the electrifying world of physics!", highlightWords: ["because", "electrifying", "physics"] },
    { time: "0:19", text: "Let's start with electric charge. Every atom is made up of protons, neutrons, and electrons.", highlightWords: ["charge", "atom", "protons", "proton", "neutrons", "neutron", "electrons", "electron"] },
    { time: "0:27", text: "Protons carry a positive charge, while electrons carry a negative charge, and neutrons are neutral.", highlightWords: ["protons", "proton", "positive", "while", "electrons", "electron", "negative", "neutrons", "neutron", "neutral", "charge"] },
    { time: "0:33", text: "When an object gains or loses electrons, it becomes electrically charged.", highlightWords: ["when", "gains", "loses", "electrons", "electron", "charged", "charge"] },
    { time: "0:38", text: "For example, rub that balloon on your pullover and bam—the balloon steals some electrons from your pullover, giving your pullover a positive charge.", highlightWords: ["for example", "rub", "balloon", "pullover", "steals", "steal", "electrons", "electron", "positive", "charge"] },
    { time: "0:48", text: "Charged objects can attract or repel each other: Opposites attract and like charges repel. Simple right?", highlightWords: ["charged", "charge", "attract", "repel", "opposites"] },
    { time: "0:57", text: "Now let's talk about the electric field.", highlightWords: ["now", "field"] },
    { time: "1:00", text: "Imagine an invisible force field around any charged object—this is the electric field.", highlightWords: ["invisible", "field", "charged", "charge"] },
    { time: "1:05", text: "It tells other charges how to move. Think of it like a map for charges to follow.", highlightWords: ["move", "think of it like", "map", "charges", "charge"] },
    { time: "1:10", text: "The direction of the field? Easy: it points away from positive charges and toward negative charges.", highlightWords: ["direction", "positive", "negative", "charges", "charge", "field"] },
    { time: "1:17", text: "The stronger the charge, the stronger the field.", highlightWords: ["stronger", "charge", "field"] },
    { time: "1:21", text: "And here's the cool part: electric fields are everywhere! They govern how charges interact across space.", highlightWords: ["here's the cool part", "fields", "field", "govern", "interact", "charges", "charge", "space"] },
    { time: "1:28", text: "Electric charges and fields aren't just cool science—they power our world, from how electricity flows through wires to how lightning forms in a storm.", highlightWords: ["charges", "charge", "fields", "field", "power", "electricity", "flows", "flow", "wires", "lightning", "storm"] },
    { time: "1:38", text: "This phenomenon is the spark behind it all.", highlightWords: ["phenomenon", "spark"] },
    { time: "1:41", text: "So the next time you feel that static zap or see a lightning bolt, you'll know it's all about electric charges and fields at work!", highlightWords: ["so", "static zap", "lightning bolt", "lightning", "charges", "charge", "fields", "field"] },
    { time: "1:48", text: "If you found this shocking (pun intended), like, subscribe, and share. Let's keep the sparks flying! See you next time.", highlightWords: ["shocking", "sparks flying", "spark"] }
];

const MICROTEACHING_QUIZ = [
    {
        id: "q1",
        question: "According to the video, what subatomic particles carry a negative charge and can be 'stolen' when rubbing a balloon on a pullover?",
        options: ["Protons", "Electrons", "Neutrons", "Photons"],
        correct: 1,
        explanation: "Electrons carry a negative charge and reside in atomic orbitals where friction can transfer them between materials (triboelectric charging)."
    },
    {
        id: "q2",
        question: "What happens when two objects with LIKE (identical) charges are placed close to each other in space?",
        options: ["They attract each other along a straight line.", "They neutralize instantly into neutrons.", "They repel each other with an electrostatic force.", "They generate no force whatsoever."],
        correct: 2,
        explanation: "Coulomb's Law states that like charges repel (`+` and `+` or `-` and `-`), whereas opposite charges attract (`+` and `-`)."
    },
    {
        id: "q3",
        question: "In what direction do electric field vectors point around point charges?",
        options: ["In circles around both positive and negative charges.", "Away from positive charges and toward negative charges.", "Toward positive charges and away from negative charges.", "Strictly downward toward the center of the Earth."],
        correct: 1,
        explanation: "By universal convention, electric field lines (`E`) point AWAY from positive source charges and TOWARD negative sink charges."
    },
    {
        id: "q4",
        question: "Which of the following sentences correctly uses the academic connector 'while' to express contrast?",
        options: ["Protons carry a positive charge, while electrons carry a negative charge.", "While the balloon rubbed, lightning in the sky.", "Lightning forms in a storm while proton electron.", "We study physics while force vector."],
        correct: 0,
        explanation: "'While' is used here as a subordinating conjunction comparing two contrasting facts in parallel ('Protons carry positive... while electrons carry negative')."
    },
    {
        id: "q5",
        question: "What real-world phenomena are directly governed by electric charges and fields according to the workshop conclusion?",
        options: ["Only laboratory experiments on static cling.", "How electricity flows through wires and how lightning forms during storms.", "The gravitational orbit of planets around the sun.", "The acoustic speed of sound in vacuum."],
        correct: 1,
        explanation: "Electric charges and fields govern electromagnetic interactions across space, powering everything from electrical currents in wires to high-voltage lightning discharges."
    }
];

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { MICROTEACHING_VOCABULARY, MICROTEACHING_TRANSCRIPT, MICROTEACHING_QUIZ };
}
